<div x-data="confirmModal()" x-show="open" x-cloak @open-confirm-modal.window="openFromLivewire($event.detail[0])" @keydown.escape.window="close()" class="fixed inset-0 z-[60] flex items-center justify-center p-4" role="dialog" aria-modal="true" aria-labelledby="confirm-modal-title">
    <div class="absolute inset-0 bg-slate-950/45" x-transition.opacity @click="close()"></div>
    <div x-ref="dialog" x-show="open" x-transition:enter="transition ease-out duration-200" x-transition:enter-start="translate-y-2 opacity-0" x-transition:enter-end="translate-y-0 opacity-100" x-transition:leave="transition ease-in duration-150" x-transition:leave-start="translate-y-0 opacity-100" x-transition:leave-end="translate-y-2 opacity-0" @keydown.tab.prevent="trapFocus($event)" class="relative w-full max-w-md rounded-xl bg-white p-6 shadow-2xl">
        <div class="flex items-start gap-4"><div class="flex h-10 w-10 shrink-0 items-center justify-center rounded-full" :class="type === 'danger' ? 'bg-red-100 text-red-700' : 'bg-amber-100 text-amber-700'"><svg class="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" :d="type === 'danger' ? 'M6 18 18 6M6 6l12 12' : 'M12 9v4m0 4h.01M10.3 3.9 1.8 18a2 2 0 0 0 1.7 3h17a2 2 0 0 0 1.7-3L13.7 3.9a2 2 0 0 0-3.4 0Z'" /></svg></div><div class="min-w-0 flex-1"><h3 id="confirm-modal-title" class="text-base font-semibold text-slate-900" x-text="title"></h3><p class="mt-2 text-sm leading-6 text-slate-600" x-text="message"></p></div></div>
        <div class="mt-6 flex justify-end gap-3"><button type="button" @click="close()" class="app-button-secondary">Batal</button><button type="button" x-ref="confirmButton" @click="confirm()" class="app-button text-white" :class="type === 'danger' ? 'bg-red-600 hover:bg-red-700' : 'bg-amber-500 hover:bg-amber-600'" x-text="confirmText"></button></div>
        <form x-ref="confirmForm" method="POST" class="hidden">@csrf <input x-ref="methodField" type="hidden" name="_method" value="DELETE"></form>
    </div>
</div>
<script>
function confirmModal() { return { open:false,type:'danger',title:'',message:'',confirmText:'',actionUrl:'',actionMethod:'DELETE',formId:'',livewireAction:'',livewireParams:[],previousFocus:null,
init(){ window.openConfirmModal=o=>{this.assign(o);this.openDialog()};window.openConfirmFromEl=e=>window.openConfirmModal({type:e.dataset.type,title:e.dataset.title,message:e.dataset.message,confirmText:e.dataset.confirmText,actionUrl:e.dataset.actionUrl,actionMethod:e.dataset.actionMethod,formId:e.dataset.formId}) },
assign(o={}){this.resetState();this.type=o.type||'danger';this.title=o.title||'Konfirmasi';this.message=o.message||'Apakah Anda yakin?';this.confirmText=o.confirmText||'Ya, lanjutkan';this.actionUrl=o.actionUrl||'';this.actionMethod=o.actionMethod||'DELETE';this.formId=o.formId||'';this.livewireAction=o.livewireAction||'';this.livewireParams=o.livewireParams||(o.roleId!==undefined?[o.roleId]:[])},openFromLivewire(o){this.assign(o);this.openDialog()},openDialog(){this.previousFocus=document.activeElement;this.open=true;document.body.classList.add('overflow-hidden');this.$nextTick(()=>this.$refs.confirmButton.focus())},close(){if(!this.open)return;this.open=false;document.body.classList.remove('overflow-hidden');this.$nextTick(()=>{this.previousFocus?.focus();this.resetState()})},confirm(){const f=this.formId,a=this.livewireAction,p=this.livewireParams,u=this.actionUrl,m=this.actionMethod;this.close();if(f)document.getElementById(f)?.submit();else if(a)Livewire.dispatch('call-livewire-action',{action:a,params:p});else if(u){const form=this.$refs.confirmForm;form.action=u;this.$refs.methodField.value=m;form.submit()}},trapFocus(e){const x=[...this.$refs.dialog.querySelectorAll('button:not([disabled]),[href],input:not([type=hidden]):not([disabled]),select:not([disabled]),textarea:not([disabled])')],f=x[0],l=x.at(-1);if(e.shiftKey&&document.activeElement===f)l.focus();else if(!e.shiftKey&&document.activeElement===l)f.focus();else return},resetState(){this.type='danger';this.title='';this.message='';this.confirmText='';this.actionUrl='';this.actionMethod='DELETE';this.formId='';this.livewireAction='';this.livewireParams=[]} } }
</script>
